name: Generate HTML on PR merge

on:
pull_request:
branches:
- master

jobs:
generate-html:
runs-on: windows-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
  - name: Install dependencies
    run: |
      choco install nodejs -y --version=14.18.0
      npm install

  - name: Generate HTML
    run: |
      node generate-html.js

  - name: Commit files
    uses: EndBug/add-and-commit@v7
    with:
      author_name: GitHub Actions Bot
      author_email: actions@github.com
      message: "Add generated HTML file"
      files: |
        ./index.html

  - name: Push changes
    uses: ad-m/github-push-action@v0.7.0
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}

